# # .pre-commit-config.yaml
# repos:
#   - repo: https://github.com/kynan/nbstripout
#     rev: 0.6.1
#     hooks:
#       - id: nbstripout


repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - --keep-output
          - --extra-keys
          - metadata.execution_count
